server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  servlet:
    context-path: /sas-client
# 腾讯云地址
tencent:
  path: https://lulu0921-1305401030.cos.ap-guangzhou.myqcloud.com
spring:
  application:
    name: sas-client
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1939945226@qq.com
    password: znnuukqnmhshbdef

sas:
  jwt:
    secret: 123456  #秘钥
    expire: 5          #过期时间
    cache-expire: 10   #缓存过期时间
  face:
    createFaceModelUrl: http://192.168.56.1:3000/create_face_model
    checkinUrl: http://192.168.56.1:3000/checkin
  email:
    system: 937967447@qq.com
    hr: 1939945226@qq.com
  code: HelloWorld
  image-folder: E:/sas/image

wx:
  app-id: wx887b6ed5a186a547
  app-secret: 8305080da6dd9aa85793c493b0135621




